version: '3.8'

services:
  chat-backend:
    image: gurudeep16/chatapp-backend:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/chatapp
      - SPRING_DATASOURCE_USERNAME=gudii16
      - SPRING_DATASOURCE_PASSWORD=allBest
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: chatAppDb
    environment:
      POSTGRES_DB: chatapp
      POSTGRES_USER: gudii16
      POSTGRES_PASSWORD: allBest
    ports:
      - "5432:5432"